name: Deltalake lambda layer build
on:
    workflow_dispatch:
    push:
        branches: [ main ]
        paths:
            - "infrastructure/lambda_layers/delta-rs/requirements.txt"
            - ".github/workflows/delta-lambda-layer-build.yml"
permissions:
    id-token: write
    contents: read
concurrency:
    group: deltalake-lambda-layer-build-main
jobs:
    layer_build:
        runs-on: ubuntu-latest
        container:
            image: public.ecr.aws/lambda/python:3.12
        environment: main
        timeout-minutes: 30
        steps:
            - run: |
                dnf update
                dnf install git zip unzip awscli -y                
            - uses: actions/checkout@v6
            - run: pip install --upgrade pip
            - run: pip install --no-cache -r infrastructure/lambda_layers/delta-rs/requirements.txt -t asset/python/lib/python3.12/site-packages
            - working-directory: asset
              run: zip -r ../deltalake_layer.zip python -x "*.pyc" "*.pyo" "*__pycache__*" "*.dist-info*" "*.egg-info*" "tests" "docs" "examples" ".ruff_cache" ".mypy_cache" ".pytest_cache"
            - uses: aws-actions/configure-aws-credentials@v6
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            - run: |
                aws lambda publish-layer-version \
                --layer-name deltalake \
                --compatible-runtimes python3.12 \
                --compatible-architectures x86_64 \
                --zip-file fileb://deltalake_layer.zip
                
